package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"forum/model"
	"sync"
)

var commentSubscribers = make(map[uint]chan *model.Comment)
var mu sync.Mutex

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string, commentsLocked *bool) (*model.Post, error) {
	return r.Db.CreatePost(title, content, commentsLocked)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID uint, parentIDI *uint, parentIDS *string, content string) (*model.Comment, error) {
	res, err := r.Db.CreateComment(postID, parentIDI, parentIDS, content)
	if err != nil {
		return nil, err
	}
	mu.Lock()
	for _, ch := range commentSubscribers {
		ch <- res
	}
	mu.Unlock()
	return res, nil
}

// LockComments is the resolver for the lockComments field.
func (r *mutationResolver) LockComments(ctx context.Context, postID uint) (*model.Post, error) {
	return r.Db.LockComments(postID)
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	return r.Db.Posts()
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id uint) (*model.Post, error) {
	return r.Db.Post(id)
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, id *uint, first *int, after *string) (*model.CommentConnection, error) {
	return r.Db.Comments(id, first, after)
}

// NewComment is the resolver for the newComment field.
func (r *subscriptionResolver) NewComment(ctx context.Context, postID uint) (<-chan *model.Comment, error) {
	mu.Lock()
	defer mu.Unlock()
	ch := make(chan *model.Comment, 1)
	commentSubscribers[postID] = ch
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
